- run.go
https://github.com/microsoft/playwright/commit/4e5007ae1abe58455e64e4cf32a202c054965227
> roll(pw): to 1598658542214

- browser_type.go
- browser_type_test.go
- element_handle.go
- element_handle_test.go
- frame.go
- helper_test.go
- helpers_test.go
- js_handle.go
- page.go
- scripts/validateAPI.js
- type_helpers.go
> chore: add missing methods

- helper_test.go
Applying https://github.com/tensorflow/tensorboard/pull/3128
Upstream issue: https://github.com/golang/go/issues/32350
> fix: Windows/firefox CI build

- browser.go
- browser_test.go
> fix: browser isConnected handling

- .gitignore
- run.go
> feat: support specifying a custom driver location

- run.go
Visual Studio Code sets this environment variable in their debug terminal.
> chore: fixed when NODE_OPTIONS env was set

- browser.go
- browser_context.go
- browser_context_test.go
- element_handle.go
- element_handle_test.go
- examples/end-to-end-testing/main.go
- examples/video/main.go
- frame.go
- frame_test.go
- generated_interfaces.go
- helper_test.go
- input.go
- input_test.go
- page.go
- page_test.go
- run.go
- scripts/data/interfaces.json
- scripts/validate-interfaces.js
- videoImpl.go
- video_test.go
> chore: add missing methods: video and standardised naming

- generated_interfaces.go
- page.go
- scripts/data/interfaces.json
- scripts/generate-interfaces.js
- scripts/helpers.js
- scripts/validate-interfaces.js
> chore: add comments to generated interfaces

- frame.go
- generated_interfaces.go
- helper_test.go
- page.go
- page_test.go
- scripts/data/interfaces.json
Relates #34 
add below methods:
Frame.Tap
Page.Frame
Page.Tap
> add missing methods

- page.go
- tests/assets/error.html
- tests/page_test.go
> feat: add Page on pageerror event

- browser_context.go
- event_emitter.go
- event_emitter_test.go
- frame.go
- generated_interfaces.go
- helpers.go
- page.go
- scripts/data/interfaces.json
- websocket.go
drive-by: add unit test cleanup for event emitter edge case.
> chore: waitForEvent cleanup

- binding_call.go
- browser_context.go
- frame.go
- generated_interfaces.go
- js_handle.go
- page.go
- scripts/data/interfaces.json
- tests/binding_test.go
- tests/browser_context_test.go
- tests/browser_test.go
> tests: added more tests

- element_handle.go
- frame.go
- generated_interfaces.go
- page.go
- scripts/data/interfaces.json
- scripts/validate-interfaces.js
- tests/element_handle_test.go
> chore: add missing v1.8 methods

- element_handle.go
- generated_interfaces.go
- scripts/data/interfaces.json
- scripts/generate-api.sh
- tests/element_handle_test.go
Relates #34 
ElementHandle.WaitForElementState
ElementHandle.WaitForSelector
> add ElementHandle.WaitForElementState/WaitForSelector methods

- browser_context.go
- channel.go
- generated_interfaces.go
- helpers.go
- scripts/data/interfaces.json
- scripts/generate-api.sh
- scripts/validate-interfaces.js
- tests/browser_context_storage_state_test.go
> feat: add storage state support

- run.go
> feat(install): allow to install and skip certain browser

- element_handle.go
- generated_interfaces.go
- scripts/data/interfaces.json
- tests/element_handle_test.go
- tests/input_test.go
> fix: ElementHandle.Type

- browser.go
- browser_context.go
- cdp_session.go
- generated_interfaces.go
- objectFactory.go
- scripts/data/interfaces.json
- scripts/validate-interfaces.js
- tests/browser_context_test.go
- tests/browser_test.go
- tests/cdp_session_test.go
Let me know if the change looks good or anything I can improve. Thank you!
> added support for CDPSession

- errors.go
- tests/assets/error.html
- tests/helper_test.go
- tests/page_test.go
Introduced in https://github.com/mxschmitt/playwright-go/pull/156
> test: fix error parsing test

- generated-enums.go
- generated-structs.go
- generated_interfaces.go
- page.go
- patches/main.patch
- scripts/data/interfaces.json
- scripts/generate-api.sh
- tests/page_test.go
> fix: re-introduce Page.emulateMedia

- generated-structs.go
- patches/main.patch
> fix: add missing PagePdfOptions options

- generated_interfaces.go
- scripts/generate-interfaces.js
> chore: remove c# comments

- .github/workflows/docs.yml
- .gitignore
- 404.html
- _config.yml
- docs/.gitignore
- docs/Gemfile
- docs/Gemfile.lock
> devops: deploy to GitHub Pages manually

- browser.go
- browser_context.go
- generated-structs.go
- patches/main.patch
- tests/browser_context_storage_state_test.go
> chore: add contextstorage tests

- browser.go
- browser_context.go
- browser_type.go
- generated-structs.go
- helpers.go
- network.go
- page.go
- patches/main.patch
- route.go
Fixes https://github.com/mxschmitt/playwright-go/issues/104
> chore: add env option to browser launch

- run.go
- transport.go
> fix: defunct processes

- browser_type.go
- connection.go
- frame.go
- tests/browser_type_test.go
- tests/helper_test.go
- tests/remote_server_unix_test.go
- tests/remote_server_windows_test.go
- transport.go
> chore: cleanup websocket transport

- channel_owner.go
- connection.go
> chore: hide Dispose method

- browser_type.go
- generated-structs.go
- generated_interfaces.go
- patches/main.patch
- scripts/data/interfaces.json
- tests/browser_type_test.go
- transport.go
Closes https://github.com/mxschmitt/playwright-go/issues/194
Closes https://github.com/mxschmitt/playwright-go/issues/177
> chore: add browsertypeconnectoptions

- README.md
> docs: install guide

- .github/workflows/build.yml
- README.md
- binding_call.go
- browser.go
- browser_type.go
- channel_owner.go
- connection.go
- generated-enums.go
- generated-structs.go
- generated_interfaces.go
- go.mod
- go.sum
- jsonPipe.go
- network.go
- objectFactory.go
- page.go
- patches/main.patch
- response.go
- run.go
- tests/browser_type_test.go
- tests/page_test.go
- tests/route_test.go
- tracing.go
- transport.go
- video.go
> chore: roll to tot

- tests/browser_type_test.go
This is causing timeout errors
> fix: remove parallel exec

- browser_context.go
- generated-interfaces.go
- network.go
- request.go
- response.go
- scripts/data/interfaces.json
- scripts/generate-api.sh
- tests/page_test.go
- tests/route_test.go
> chore: fix network

- README.md
- run.go
FIxes https://github.com/mxschmitt/playwright-go/issues/209
> chore: roll driver, fix driver wait until exit

- run.go
Fixes https://github.com/mxschmitt/playwright-go/issues/144
> chore: add verbose mode to downloader

- generated-structs.go
- patches/main.patch
Fixes https://github.com/playwright-community/playwright-go/pull/255
> chore: add FirefoxUserPrefs

- run.go
> Add platform "mac-arm64" and "linux-arm64"

- generated-interfaces.go
- locator.go
- scripts/data/interfaces.json
- tests/locator_test.go
This implementation fix use LocatorOptions for Page and Locator.
Related issue is #274
> sttaran // fixed the use of Locator options

- frame.go
- frame_locator.go
- generated-interfaces.go
- locator.go
- page.go
- scripts/data/interfaces.json
- tests/frame_locator_test.go
This is for adding FrameLocator implementation.
> feat: add frame locator

- CONTRIBUTING.md
- README.md
- frame.go
- generated-enums.go
- generated-interfaces.go
- generated-structs.go
- js_handle.go
- patches/main.patch
- run.go
- scripts/generate-api.sh
> Update to 1.25.2

- examples/use-local-chrome/main.go
Hello!
I have added an example using Chrome already installed on local machine.
The code itself is based on the code below to create the example.
https://github.com/playwright-community/playwright-go/blob/main/examples/scraping/main.go
I created the this code because I was looking for such a code myself.
If this is an example of demand, I would be happy to check.
> example: add use local chrome example

- generated-interfaces.go
- page.go
- scripts/data/interfaces.json
- tests/page_test.go
> chore: WaitForRequest/WaitForResponse accepts Options args

- README.md
> Update README with fixed example

- browser_context.go
- connection.go
- run.go
- scripts/apply-patch.sh
Hi @mxschmitt, this pr rolls to v1.36.2. playwrigh-go has fixed 2 issues since v0.3500.0, hope to tag it as v0.3600.0. thanks.
> Roll to Playwright v1.36.2

- .github/workflows/build.yml
- README.md
- artifact.go
- assertions.go
- browser.go
- connection.go
- errors.go
- examples/screenshot/main.go
- fetch.go
- frame.go
- generated-interfaces.go
- generated-structs.go
- js_handle.go
- locator.go
- page.go
- patches/main.patch
- run.go
- stream.go
- tests/browser_context_test.go
- tests/download_test.go
- tests/fetch_test.go
- tests/frame_test.go
- tests/helper_test.go
- tests/locator_test.go
- tests/page_test.go
- tests/worker_test.go
- transport.go
Rolling to playwright v1.37.1 and several bug fixes while improving test coverage.
> Roll to Playwright v1.37.1

- element_handle.go
- page.go
- tests/page_test.go
> fix: panic when screenshot with locator mask

- run.go
- run_test.go
> feat: env PLAYWRIGHT_DOWNLOAD_HOST also used to download driver

- tests/browser_context_test.go
> test: check secure cookies (close #430）

- README.md
- browser_context.go
- browser_type.go
- channel.go
- channel_owner.go
- connection.go
- event_emitter.go
- fetch.go
- generated-interfaces.go
- generated-structs.go
- go.mod
- go.sum
- har_router.go
- local_utils.go
- locator.go
- page.go
- patches/main.patch
- route.go
- run.go
- selectors.go
- tests/frame_locator_test.go
- tests/page_request_gc_test.go
- tests/utils_test.go
- tests/websocket_test.go
- tracing.go
- transport.go
The “RouteWebSocket” feature still needs some work, so I’ll put it in the next PR
> chore: roll to Playwright v1.48.1

- README.md
Maybe it can reduce issues related to driver version mismatch
> docs: modify the playwright driver installation instructions
