js_handle.go, js_handle_test.go
Without this, true floating point values are never returned and are always truncated to integers. There is very likely a more optimized way to do this. ~~Is there a reason the value can't just be returned without casting (if it's a "number")?~~ Duh: because it might be an integer and not a floating point.
=> return float64s from JSHandle

examples/video/main.go
Before this change empty video files were created. Seen on Ubuntu 20.04.1 LTS running under WSL2.
=> Fix bug in videos example: close page

element_handle.go, tests/element_handle_test.go
=> fix(ElementHandle): don't panic when QuerySelector not exists

README.md
Slight URL change to fix a broken link to Playwright API documentation.
=> docs: update link to Playwright API

browser.go, browser_context.go, browser_type.go, generated-structs.go, patches/main.patch
This patch should allow something like that:
```go
browser, err := pw.Chromium.Launch(playwright.BrowserTypeLaunchOptions{Headless: playwright.Bool(false), Args: []string{"--start-maximized"}})
if err != nil {
log.Fatalf("could not launch browser: %v", err)
}
page, err := browser.NewPage(playwright.BrowserNewContextOptions{NoViewport: playwright.Bool(true)})
if err != nil {
log.Fatalf("could not create page: %v", err)
}
if _, err = page.Goto("https://news.ycombinator.com"); err != nil {
log.Fatalf("could not goto: %v", err)
}
```
Fixes https://github.com/playwright-community/playwright-go/issues/245
=> chore: add support for noViewport

frame.go, generated-interfaces.go, generated-structs.go, locator.go, page.go, patches/main.patch, scripts/data/interfaces.json, tests/locator_test.go
This is implementation for `Locator` (#238).
Please review the implementations.
thank you!
=> feat: add locator functionality (#238)

.github/workflows/build.yml, browser.go, browser_context.go, browser_type.go, generated-structs.go, page.go, patches/main.patch, tests/browser_context_test.go
This implementation adds support for Har recording option.
Related issue is #253.
=> feat: support Har recording option (#253)

examples/mobile-and-geolocation/main.go
attribute `data-original-title` has changed to `data-bs-original-title` in the openstreetmap.org website
=> chore: fix attribute changes to Show My Location link in openstreetmap

frame.go, tests/frame_test.go
fixes: #285 
`PageWaitForNavigationOptions` is constructed only with URL and if the options are provided then those are explicitly set in the instance otherwise `WaitForNavigation` will use the default options
=> fix: WaitForURL use default configurations if not provided

CONTRIBUTING.md
Update the test command used in contributing guide to run all the tests on local before creating a PR
the existing commands do not run all the test and only run a subset of it in the main package whereas the test in `tests` folders are not executed
=> fix: update the command in contributing

README.md, browser.go, browser_context.go, browser_type.go, examples/end-to-end-testing/main.go, frame.go, generated-interfaces.go, generated-structs.go, locator.go, locator_helpers.go, page.go, patches/main.patch, request.go, response.go, route.go, run.go, run_test.go, tests/browser_context_test.go, tests/helper_test.go, tests/input_test.go, tests/locator_test.go, tests/selectors_get_by_test.go, tests/selectors_text_test.go, web_error.go
- roll to v1.38.1
- add some tests, and `escapeRegexForSelector` without "insert a backslash to even number of backslashes followed by the quote", it seems no error
- `PlaywrightDriver.Uninstall` for user case #372
=> Roll to Playwright v1.38.1

.github/workflows/build.yml
Most likely the X server has not been released by the previous test, so add `-a`, aka `--auto-servernum`
=> ci: xvfb-run occasionally fails when test examples

locator.go
When I use the code below, an error will be thrown
painc: interface conversion: interface {} is nil, not string
```
locator = locator.Filter(playwright.LocatorFilterOptions{
HasNotText: "test",
})
```
I checked the source code and the value obtained here is wrong
```
if option.HasNotText != nil {
selector += fmt.Sprintf(` >> internal:has-not-text=%s`, escapeForTextSelector(option.HasText, false))
}
```
=> fix: selector option.HasNotText

browser.go, browser_type.go, fetch.go, helpers.go, helpers_test.go, page.go, tests/page_test.go
`transformOptions` was previously restricted and does not report misuse. 
Now no longer restricted, and it is more intuitive to take `overrides` as the second argument when calling it.
=> fix: prevent misuse of transformOptions

README.md, assertions.go, browser_context.go, examples/end-to-end-testing/main.go, frame.go, generated-enums.go, generated-interfaces.go, generated-structs.go, glob.go, glob_test.go, go.mod, go.sum, har_router.go, helpers.go, input_files_helper.go, locator_assertions.go, page.go, page_assertions.go, patches/main.patch, request.go, route.go, run.go, tests/browser_context_test.go, tests/file_chooser_test.go, tests/frame_test.go, tests/har_test.go, tests/input_test.go, tests/locator_test.go, tests/page_test.go, tests/unroute_behavior_test.go
In addition, the last added `route` is matched first, which is consistent with the upstream.
=> Roll to Playwright v1.41.1

tests/browser_context_storage_state_test.go, type_helpers.go
This PR avoids manual conversion when there is no need to store StorageState as a file (solve #414)
```go
storageState, _ = context1.StorageState()
context2, _ := browser.NewContext(
playwright.BrowserNewContextOptions{
StorageState: storageState.ToOptionalStorageState(),
})
```
=> feat: StorageState can convert to OptionalStorageState (close #414)

.github/workflows/build.yml, run.go
close #421
By the way, rolling to v1.41.2
=> fix: correct download url for beta driver

README.md, tests/helper_test.go, tests/utils_test.go
Split the code and add comments, now `helper_test.go` can be used as a useful example
=> refactor(test): helper_test.go as a useful example

Dockerfile.example, README.md
This example Dockerfile ensures that the playwright driver version matches `go.mod`
=> docs: add Dockerfile example

browser_context.go, channel_owner.go, connection.go, event_emitter.go, internal/safe/map.go, page.go, tests/binding_test.go
=> fix: data races in some situations

.github/workflows/build.yml, frame.go, patches/main.patch, run.go
I just noticed that the Firefox [issue](https://github.com/microsoft/playwright/issues/30705) has been fixed. So this PR also changes `macos-13` back to `macos-latest`.
=> chore: roll to Playwright v1.47.1

run.go
Playwright uses `PLAYWRIGHT_BROWSERS_PATH` to define the cache directory used to install the browsers.
See playwright implementation - [link](https://github.com/microsoft/playwright/blob/470b1b4922a665d2b4230dacde16be6593b5e80c/packages/playwright-core/src/server/registry/index.ts#L275)
```go
const envDefined = getFromENV('PLAYWRIGHT_BROWSERS_PATH');
if (envDefined === '0') {
result = path.join(__dirname, '..', '..', '..', '.local-browsers');
} else if (envDefined) {
result = envDefined;
} else {
let cacheDirectory: string;
if (process.platform === 'linux')
cacheDirectory = process.env.XDG_CACHE_HOME || path.join(os.homedir(), '.cache');
else if (process.platform === 'darwin')
cacheDirectory = path.join(os.homedir(), 'Library', 'Caches');
else if (process.platform === 'win32') …
```
=> Use `PLAYWRIGHT_DRIVER_PATH` environment variable as driver cache directory

browser_context.go, channel.go, connection.go, event_emitter.go, frame_locator.go, go.mod, go.sum, internal/multierror/multierror_g0120.go, internal/multierror/multierror_go119.go, internal/safe/map.go, locator.go, page.go, run.go, tests/browser_type_test.go, tests/input_test.go
Will require go v1.22+ starting with version `v0.4800.0`. The benefit is the functionality of the new standard library, especially `errors` support for wrapping multiple errors.
=> chore: require go v1.22

element_handle.go, helpers.go, tests/element_handle_test.go
The `boundingBox` playwright API may return `nil` for the bounding box without setting an error.
The Go implementation doesn't support this case, causing null dereference and panics when trying to remap the nil to the matching struct.
We handle this by checking if the value is `nil` before remapping values.
This PR fixes this bug by checking for `nil` value before remapping.
We can also change the implementation of the remapping but it will require passing pointer to a pointer (`**`) in order to set `nil` values for variables.
Reference - https://github.com/microsoft/playwright/blob/59a50cf59603850c645830a17ccb05178eb96f50/packages/playwright-core/src/client/elementHandle.ts#L185
```
/usr/local/go/src/runtime/panic.go:785 +0x124
reflect.flag.mustBe(...) …
```
=> fix: Panics caused by BoundingBox API returning nil

browser_context.go, channel.go, channel_owner.go, connection.go, generated-interfaces.go, generated-structs.go, har_router.go, local_utils.go, objectFactory.go, page.go, patches/main.patch, route.go, run.go, selectors.go, tests/browser_context_test.go, tests/route_web_socket_test.go, tests/utils_test.go, websocket_route.go
WebSocket routing is finally available. During my testing, I found and fixed some things I missed before, such as route handler error handling, etc.
=> feat: add WebSocket routing

run.go, run_test.go
I am looking to add the feature defined in the docs here: https://playwright.dev/docs/browsers#optimize-download-size-on-ci so that I can reduce the amount of space used by downloading browsers. I only need to use the shell.
=> Add only-shell option to run options

README.md, browser_type.go, frame.go, frame_locator.go, generated-enums.go, generated-interfaces.go, generated-structs.go, locator.go, patches/main.patch, run.go, tests/fetch_test.go, tests/locator_test.go, tests/page_test.go
IndexedDB in StorageState is not yet implemented. Will do when I have time.
=> chore: roll to Playwright v1.51.1

request.go
I don't know why we need a full response object to get request sizes, but this panics for me several times per page load as I attempt to log size information
=> fix: prevent panic in Sizes()

waiter.go, waiter_test.go
for errChan cap is 1 and receive both event timeout err and callback err( block on the err for errChan handle receiving(wait#waitFunc) after callback send err(waiter#RunAndWait) ).
```go
uploadFileTimeout := 30 * 1000.0
fileChooser, err := page.ExpectFileChooser(func() error {
err = page.Locator(".fileChooser-trigger").Click(playwright.LocatorClickOptions{
Timeout: playwright.Float(40 * 1000),
})
if err != nil {
return fmt.Errorf("trigger fileChooser: %w", err)
}
return nil
}, playwright.PageExpectFileChooserOptions{
Timeout: playwright.Float(uploadFileTimeout),
})
if err := fileChooser.SetFiles(filepaths); err != nil {
return "", fmt.Errorf("set files: %w", err)
}
```
```go
stopped := false
defer func() {
stopped = true
}()
topContext := context.Background()
uploadFileTimeout := 30 * …
```
=> fix: waiter#RunAndWait maybe cause deadlock.
